### ISSUE TITLE
Carrier Captain slot validation error

### ISSUE THREAD

**Issue by klauskopec** [achapin/homeworldfleetcommand-forcebuilder#2]
Carrier Captain must be put on a Carrier or Mothership, but the slot validation allows this slot to be taken by other super-capital ships (e.g., Destroyer) without showing an error.

**Comment by achapin** [comment]
I'm not sure I grok the issue here. I checked it out, and the Carrier Captain can go on Carriers or Motherships, but not Destroyers.

https://github.com/achapin/homeworldfleetcommand-forcebuilder/assets/4753012/6c7b1ce6-bcac-49ba-a33b-8661907644e8

Is the issue that the Unit Tab given by the Carrier Captain for a super-capital ship can be used by a different ship? I don't think that's illegal. It's just +1, and as long as all Units are in available Unit Tabs, then everything is fine.

**Comment by klauskopec** [comment]
It's the latter, i.e. about which unit uses which tab.

The rules sttae on page 41: "When purchasing a unit with the compulsory tab on a Leader card, that card must be assigned to the purchased unit."

Imagine a force with only the Carrier Captain giving you a single Super Cap slot and no other  super cap slots available. The app currently allows you to add a destroyer into that slot. But the rule forces you to add the leader to the ship, because it's a compulsory tab on the Carrier Captain,see rules quote above. However Carrier Captain is only for Carriers (Taiidan) or for Carriers& Mothership (Kushan).

So you're now in an invalid situation in the app because all you have is the destroyer to which you (correctly) cannot add the leader, but you must add this eader to it because it gave you the compulsory slot. 

Hope that makes sense.

**Comment by achapin** [comment]
Roger, understood. Though I'm not sure if it's a problem worth solving. If you go about it that way, the Carrier Captain isn't actually being assigned automatically to the Destroyer in the app. The point of the app is to let you play around with the force composition. My assumption is that once the force is "finished", then its final state is the one which would be evaluated for validating. 

In that case of a force with just a Carrier Captain and a Destroyer, the CC  is unassigned because they can't legally be added to the Destroyer. As far as I know a legal Force can't have any unassigned leaders. Maybe the simpler fix would be making it clearer that a force isn't legal unless all leaders are assigned?

I'm not trying to avoid responsibility here. I'm just concerned that implementing the auto-assign rigidly would be a worse user experience for no real benefit.

**Comment by klauskopec** [comment]
I like the idea to have a "illegal force" information text. That's what another list builder I worked on also had for competetive rules. They were not enforced, but shown as warnings.

Let's do that instead, it's also easier and might come in handy if we ever find another aspect we want to warn or inform users about
